[autentication]
api_key = ''
api_key_secret = ''
access_token = ''
access_token_secret = ''


[download_tweets_from_list]
tweets_list_file = "../../datasets/anderson/tweet_ids.txt"
saved_tweets_log = "../data/downloaded_tweets"
save_on = "../data/tweets/"
start_by_line = 171045
